# Generated by Django 6.1.1 on 2026-09-11 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bosqich nomi')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('max_duration_hours', models.FloatField(default=0, verbose_name='Maksimal vaqt (soat)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Rahbar'), ('DISPATCHER', 'Dispetcher / Operator'), ('WORKER', 'Ishchi'), ('INSPECTOR', 'Nazoratchi')], max_length=20, verbose_name='Lavozim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.stage', verbose_name='Biriktirilgan bosqich')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Buyurtma №')),
                ('client_name', models.CharField(max_length=255, verbose_name='Mijoz F.I.Sh.')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('product_type', models.CharField(max_length=100, verbose_name='Mahsulot turi')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='O‘lchamlari')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material rangi')),
                ('hardware', models.CharField(blank=True, max_length=255, null=True, verbose_name='Furnitura')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('deadline', models.DateTimeField(verbose_name='Muddat')),
                ('priority', models.CharField(choices=[('NORMAL', '🟢 Oddiy'), ('MEDIUM', '🟡 O‘rtacha'), ('HIGH', '🔴 Yuqori'), ('URGENT', '⚫ Shoshilinch')], default='NORMAL', max_length=20, verbose_name='Ustuvorlik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tayyor')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to='production.employee', verbose_name="Mas'ul menejer")),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_orders', to='production.stage', verbose_name='Joriy bosqich')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='production.order')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('IN_PROGRESS', 'Jarayonda'), ('WAITING', 'Kutmoqda'), ('DELAYED', 'Kechikkan'), ('PROBLEM', 'Muammoli'), ('CANCELED', 'Bekor qilingan'), ('COMPLETED', 'Tayyor'), ('PAUSED', 'Pauza')], default='NEW', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='production.order')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.stage')),
            ],
        ),
    ]
